Repository projectsyn/component-espejote, pull requests merged in 2025-08, with the labels that each got.

#19 Update ghcr.io/vshn/espejote Docker tag to v0.9.2
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: dependency, bump:patch

#20 Update ghcr.io/vshn/espejote Docker tag to v0.10.0
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: bump:minor, dependency

#22 Fix broken `roleRef` for supplemental cluster roles
  component/main.jsonnet
  tests/golden/resources/espejote/espejote/44_supplemental_cluster_role_my-namespace_copy-configmap.yaml
Labels: bug, bump:patch
