Repository projectsyn/component-espejote, pull requests merged in 2025-03, with the labels that each got.

#2 Add basic `Admission` creation helper
  lib/espejote.libsonnet
Labels: enhancement, bump:minor

#5 Update ghcr.io/vshn/espejote Docker tag to v0.5.0
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/crd/apiextensions.k8s.io_v1_customresourcedefinition_managedresources.espejote.io.yaml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/crd/apiextensions.k8s.io_v1_customresourcedefinition_managedresources.espejote.io.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: bump:minor, dependency

#6 Update ghcr.io/vshn/espejote Docker tag to v0.5.1
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: dependency, bump:patch
