Repository projectsyn/component-espejote, pull requests merged in 2025-05, with the labels that each got.

#11 Update ghcr.io/vshn/espejote Docker tag to v0.6.0
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: bump:minor, dependency

#15 Update ghcr.io/vshn/espejote Docker tag to v0.8.0
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: dependency

#14 Alerts and runbooks for them
  class/defaults.yml
  docs/modules/ROOT/pages/runbooks/EspejoteAbnormalReconciles.adoc
  docs/modules/ROOT/pages/runbooks/EspejoteAdmissionErrors.adoc
  docs/modules/ROOT/pages/runbooks/EspejoteManagedResourceNotReady.adoc
  docs/modules/ROOT/pages/runbooks/EspejoteManagedResourceReadynessChanges.adoc
  docs/modules/ROOT/pages/runbooks/EspejoteOutOfMemoryEvents.adoc
  docs/modules/ROOT/pages/runbooks/_RuleTemplate.adoc
  docs/modules/ROOT/partials/nav.adoc
  docs/modules/ROOT/partials/runbooks/contribution_note.adoc
  tests/golden/defaults/espejote/espejote/30_alerts.yaml
  tests/golden/resources/espejote/espejote/30_alerts.yaml
Labels: enhancement, bump:minor

#13 Add helper to generate a ManagedResource for a partial cluster-scoped object
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  lib/espejote.libsonnet
  tests/golden/lib/espejote/apps/espejote.yaml
  tests/golden/lib/espejote/espejote/00_namespace.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/crd/apiextensions.k8s.io_v1_customresourcedefinition_admissions.espejote.io.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/crd/apiextensions.k8s.io_v1_customresourcedefinition_jsonnetlibraries.espejote.io.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/crd/apiextensions.k8s.io_v1_customresourcedefinition_managedresources.espejote.io.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/admissionregistration.k8s.io_v1_mutatingwebhookconfiguration_espejote-dynamic-webhook.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/admissionregistration.k8s.io_v1_validatingwebhookconfiguration_espejote-dynamic-webhook.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/cert-manager.io_v1_certificate_espejote-metrics-certs.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/cert-manager.io_v1_certificate_espejote-serving-cert.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/cert-manager.io_v1_issuer_espejote-selfsigned-issuer.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/monitoring.coreos.com_v1_servicemonitor_espejote-controller-manager-metrics-monitor.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_clusterrole_espejote-manager-role.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_clusterrole_espejote-metrics-auth-role.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_clusterrole_espejote-metrics-reader.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_clusterrolebinding_espejote-manager-rolebinding.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_clusterrolebinding_espejote-metrics-auth-rolebinding.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_role_espejote-leader-election-role.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/rbac.authorization.k8s.io_v1_rolebinding_espejote-leader-election-rolebinding.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/v1_service_espejote-controller-manager-metrics-service.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/v1_service_espejote-webhook-service.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/v1_serviceaccount_espejote-controller-manager.yaml
  tests/golden/lib/espejote/espejote/20_aggregated_cluster_role.yaml
  tests/golden/lib/espejote/espejote/30_alerts.yaml
  tests/golden/lib/espejote/tests/image_config.yaml
  tests/golden/lib/espejote/tests/image_config_override.yaml
  tests/lib.yml
  tests/test-partial-cluster-scoped-resource.jsonnet
Labels: enhancement, bump:minor

#17 Update ghcr.io/vshn/espejote Docker tag to v0.9.1
  class/defaults.yml
  tests/golden/defaults/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/lib/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
  tests/golden/resources/espejote/espejote/10_kustomize/espejote/apps_v1_deployment_espejote-controller-manager.yaml
Labels: dependency, bump:patch
